        <hr color=red />         日志级别：ERROR 记录时间：2020-06-08 00:57:31,430  记录类：HC.NewSystem.API.Controllers.OrderInfoController 线程ID：[5]        <br/>设备信息：{log4net:Identity=NOT AVAILABLE, RequestPath=/api/OrderInfo/TestLog4net, ParentId=, TraceId=29370946-4ee36cae186cdf1c, log4net:HostName=DESKTOP-T413THD, ActionName=HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net (HC.NewSystem.WebApi), SpanId=|29370946-4ee36cae186cdf1c., log4net:UserName=NOT AVAILABLE, RequestId=8000000e-0000-fe00-b63f-84710c7967bb, ActionId=27328c46-e4a8-4f40-a154-faa3b3531331}        <br/>日志信息：LogError-- 错误: 2020-06-08 00:57:31                     <hr color=red />         日志级别：ERROR 记录时间：2020-06-08 01:16:22,554  记录类：HC.NewSystem.API.Controllers.OrderInfoController 线程ID：[4]        <br/>设备信息：{log4net:UserName=NOT AVAILABLE, log4net:HostName=DESKTOP-T413THD, ActionId=398a28f7-c570-43eb-9cf8-e0cb8f9bffb4, RequestPath=/api/OrderInfo/TestLog4net, TraceId=92601c8b-4fbf7f9d94a1c16d, log4net:Identity=NOT AVAILABLE, RequestId=80000015-0006-fd00-b63f-84710c7967bb, ActionName=HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net (HC.NewSystem.WebApi), ParentId=, SpanId=|92601c8b-4fbf7f9d94a1c16d.}        <br/>日志信息：LogError-- 错误: 2020-06-08 01:16:22           <br/>               <hr color=red />         日志级别：ERROR 记录时间：2020-06-08 01:16:22,876  记录类：Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware 线程ID：[4]        <br/>设备信息：{log4net:UserName=NOT AVAILABLE, log4net:HostName=DESKTOP-T413THD, RequestPath=/api/OrderInfo/TestLog4net, TraceId=92601c8b-4fbf7f9d94a1c16d, log4net:Identity=NOT AVAILABLE, RequestId=80000015-0006-fd00-b63f-84710c7967bb, ParentId=, SpanId=|92601c8b-4fbf7f9d94a1c16d.}        <br/>日志信息：An unhandled exception has occurred while executing the request.           <br/>       System.DivideByZeroException: Attempted to divide by zero.
   at HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net() in I:\CompanyCode\HC.Core.NewSystem\HC.NewSystem.API\Controllers\OrderInfoController.cs:line 54
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
        <hr color=red />         日志级别：ERROR 记录时间：2020-06-08 01:23:21,188  记录类：HC.NewSystem.API.Controllers.OrderInfoController 线程ID：[13]        <br/>设备信息：{ActionId=67a5434d-3f31-462e-999d-7a7c9eaff087, ActionName=HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net (HC.NewSystem.WebApi), RequestId=80000007-0005-ff00-b63f-84710c7967bb, RequestPath=/api/OrderInfo/TestLog4net, ParentId=, log4net:UserName=NOT AVAILABLE, log4net:HostName=DESKTOP-T413THD, log4net:Identity=NOT AVAILABLE, TraceId=1c2e028f-4cfffaa02f2fa7ca, SpanId=|1c2e028f-4cfffaa02f2fa7ca.}        <br/>日志信息：LogError-- 错误: 2020-06-08 01:23:21           <br/>               <hr color=red />         日志级别：ERROR 记录时间：2020-06-08 01:23:21,307  记录类：HC.NewSystem.WebApi.Filters.GlobalExceptionFilter 线程ID：[13]        <br/>设备信息：{ActionId=67a5434d-3f31-462e-999d-7a7c9eaff087, ActionName=HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net (HC.NewSystem.WebApi), RequestId=80000007-0005-ff00-b63f-84710c7967bb, RequestPath=/api/OrderInfo/TestLog4net, ParentId=, log4net:UserName=NOT AVAILABLE, log4net:HostName=DESKTOP-T413THD, log4net:Identity=NOT AVAILABLE, TraceId=1c2e028f-4cfffaa02f2fa7ca, SpanId=|1c2e028f-4cfffaa02f2fa7ca.}        <br/>日志信息：Attempted to divide by zero.
【自定义错误】：Attempted to divide by zero. 
【异常类型】：DivideByZeroException 
【异常信息】：Attempted to divide by zero. 
【堆栈调用】：   at HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net() in I:\CompanyCode\HC.Core.NewSystem\HC.NewSystem.API\Controllers\OrderInfoController.cs:line 54
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)           <br/>               <hr color=red />         日志级别：ERROR 记录时间：2020-06-08 01:26:21,006  记录类：HC.NewSystem.API.Controllers.OrderInfoController 线程ID：[11]        <br/>设备信息：{log4net:UserName=NOT AVAILABLE, ActionId=fae5074c-3049-44e7-934e-34c6d09d14c3, RequestPath=/api/OrderInfo/TestLog4net, TraceId=25da30a-4457b3ec5c6d64e6, log4net:Identity=NOT AVAILABLE, log4net:HostName=DESKTOP-T413THD, ParentId=, RequestId=80000002-0002-fd00-b63f-84710c7967bb, SpanId=|25da30a-4457b3ec5c6d64e6., ActionName=HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net (HC.NewSystem.WebApi)}        <br/>日志信息：LogError-- 错误: 2020-06-08 01:26:21           <br/>               <hr color=red />         日志级别：ERROR 记录时间：2020-06-08 01:26:21,127  记录类：HC.NewSystem.WebApi.Filters.GlobalExceptionFilter 线程ID：[11]        <br/>设备信息：{log4net:UserName=NOT AVAILABLE, ActionId=fae5074c-3049-44e7-934e-34c6d09d14c3, RequestPath=/api/OrderInfo/TestLog4net, TraceId=25da30a-4457b3ec5c6d64e6, log4net:Identity=NOT AVAILABLE, log4net:HostName=DESKTOP-T413THD, ParentId=, RequestId=80000002-0002-fd00-b63f-84710c7967bb, SpanId=|25da30a-4457b3ec5c6d64e6., ActionName=HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net (HC.NewSystem.WebApi)}        <br/>日志信息：Attempted to divide by zero. 自定义错误 ：Attempted to divide by zero.  异常类型：DivideByZeroException 
 异常信息：Attempted to divide by zero. 
 堆栈调用：   at HC.NewSystem.API.Controllers.OrderInfoController.TestLog4net() in I:\CompanyCode\HC.Core.NewSystem\HC.NewSystem.API\Controllers\OrderInfoController.cs:line 54
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)           <br/>       